server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API İsteklerini Backend Container'ına Yönlendir (Port 9000 PHP-FPM)
    location /api {
        proxy_pass http://backend:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Storage İsteklerini Backend Storage Klasörüne Yönlendir
    location /storage {
        proxy_pass http://backend:9000;
        proxy_set_header Host $host;
    }
}
